### ISSUE TITLE
Add a command to clean the old setting and re-configurate

### ISSUE THREAD

**Issue by panpan0000** [XiaowenJiang/ivn#1]
1.example, I found I've already br-int created or link name veth1 existing.
2. I found eth1 is not my config, then I changed the network_configuration.yml then want to re-setup

there's no way to clean up and re-set everything, except manual cleanup

**Comment by panpan0000** [comment]
sudo ovs-vsctl remove br-int
sudo ovs-vsctl remove br-ex
sudo ip link delete veth0
sudo ip link delete veth1
sudo ip link delete veth2
sudo ip netns delete node1
sudo ip netns delete node2
sudo ip netns delete node3

**Comment by XiaowenJiang** [comment]
you could call `./creator_rackhd.py delete` to clean the environment
@panpan0000

**Comment by panpan0000** [comment]
I fount it just now . thank you
